# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f2db2ea7bfc64f69f3c03f732e348450de0a723030744322dcc941d1043152b5066e7964dd1a0e20d31e260d31776b932489c24b54e10127607f2af5e26a021

test:
  secret_key_base: c00435bb055982845a59ab00f7865fd2bab273e50a168ce24abdfe7d7a0eccffaf23a1371f8a3165cfe1f67fb59ea819fe8250d1db9e0c288c8455570f318378

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
